### ISSUE TITLE
Initial conditions

### ISSUE THREAD

**Issue by munshkr** [pabloriera/lode#5]
It should be possible to set initial conditions for an ODE. It would also be useful to add a new command for restarting the synth node, so the initial conditions take place again. In a more complex case, initial conditions could be passed down with a special type of input that triggers the system to go to that location and then continue. Example syntax:

```yaml
hopf:
  equation:
    x: '2*pi*y*w + (e*x-x*(x*x+y*y))*100.0'
    y: '-2*pi*x*w + (e*y-y*(x*x+y*y))*100.0'
  parameters:
    w: 440.0
    e: 1.0
  init:
    x: 0.5
    y: 0.5
```
