### ISSUE TITLE
Time variable

### ISSUE THREAD

**Issue by munshkr** [pabloriera/lode#6]
It should be possible to add the time variable in the equations, this is rather strait fordward to do

```yaml
hopf:
  equation:
    x: '2*pi*y*w + sin(w*t) + (e*x-x*(x*x+y*y))*100.0'
    y: '-2*pi*x*w + (e*y-y*(x*x+y*y))*100.0'
```
