### ISSUE TITLE
Output variables

### ISSUE THREAD

**Issue by munshkr** [pabloriera/lode#7]
It should be possible to select which are the output variables that will sound. Currently, each equation output is assigned to 0, 1, ...

```yaml
hopf:
  equation:
    x: '2*pi*y*w + sin(w*t) + (e*x-x*(x*x+y*y))*100.0'
    y: '-2*pi*x*w + (e*y-y*(x*x+y*y))*100.0'
  output:
    x:
      gain: 0.1
      channel: 1 
```
