### ISSUE TITLE
Delayed inputs

### ISSUE THREAD

**Issue by munshkr** [pabloriera/lode#8]
It should be possible to delay an input signal, and also in the same node (feedback)

```yaml
hopf:
  equation:
    x: '2*pi*y*w + (e*x-x*(x*x+y*y))*100.0'
    y: '-2*pi*x*w + (e*y-y*(x*x+y*y))*100.0+x(-d)'
```
